Initial commit, running Debain successfully building with Vivado 2017.1

diff --git a/piton/tools/bin/midas b/piton/tools/bin/midas
--- a/piton/tools/bin/midas
+++ b/piton/tools/bin/midas
@@ -1,24 +1,24 @@
 #! /bin/sh
 # Modified by Princeton University on June 9th, 2015
 # ========== Copyright Header Begin ==========================================
-# 
+#
 # OpenSPARC T1 Processor File: midas
 # Copyright (c) 2006 Sun Microsystems, Inc.  All Rights Reserved.
 # DO NOT ALTER OR REMOVE COPYRIGHT NOTICES.
-# 
+#
 # The above named program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public
 # License version 2 as published by the Free Software Foundation.
-# 
-# The above named program is distributed in the hope that it will be 
+#
+# The above named program is distributed in the hope that it will be
 # useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 # General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public
 # License along with this work; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA.
-# 
+#
 # ========== Copyright Header End ============================================
 #
 # .local_perlmod_wrapper
@@ -28,7 +28,7 @@
 die () {
     message="$1"
     echo "$tool -> .local_perlmod_wrapper: $message Exiting ..."
-    exit 1 
+    exit 1
 }
 
 ############################ main ##############################
@@ -42,13 +42,13 @@ TRE_TOOL2TOOLSET=${TRE_TOOL2TOOLSET:=$TRE_ROOT/tool2toolset}
 
 toolset=`awk '{if($1 == var)print $2}' var=$tool $TRE_TOOL2TOOLSET`
 if [ -z "$toolset" ] ; then
-    die "flow not found!" 
-else 
+    die "flow not found!"
+else
     TOOLSET=`echo $toolset |tr '[a-z]' '[A-Z]'`
 fi
 
-### Version may be set either by TRE or by environment variable 
-### 'VERSION_$TOOLSET', if case TRE_ENTRY is set to '/'. 
+### Version may be set either by TRE or by environment variable
+### 'VERSION_$TOOLSET', if case TRE_ENTRY is set to '/'.
 ### Either way, the version MUST be set.
 
 eval vers=\$VERSION_$TOOLSET
@@ -62,7 +62,7 @@ elif [ ! -z "$TRE_SEARCH" ] && [ ! -z "$TRE_ENTRY" ] ; then
     eval export VERSION_$TOOLSET
 else
     die "TRE_SEARCH & TRE_ENTRY are not set."
-fi    
+fi
 
 ###  VERSION_$TOOLSET **MUST** be set, even if TRE is not used.
 
@@ -70,7 +70,7 @@ if [ -z "$version" ] ; then
     die "No version set for flow '$toolset'."
 fi
 
-###  try to execute the toolset member tool 
+###  try to execute the toolset member tool
 ### (the version is passed in VERSION_$TOOLSET)
 
 # necessary for the moment
@@ -109,7 +109,7 @@ else
   PERL5OPT="-I$PERL_MODULE_BASE -I$PERL_MODULE_BASE/$OS-$CPU -I$PERL5_PATH/$PERL_VER -I$PERL5_PATH/$PERL_VER/sun4-solaris $PERL5OPT"
 fi
 export PERL5OPT
-
+echo $exe
 if [ -x $exe ] ; then
     exec $PERL_CMD $exe "$@"
 else
